CHANGELOG.md
README.md
docs/index.md

**Issue number:** #146
This PR fixes the broken links in the documentation
- Link updates
<details>
Checklist:
</details>
-----
[View rendered CHANGELOG.md](https://github.com/amirkaws/aws-lambda-powertools-dotnet/blob/amirkaws-fix-doc-links/CHANGELO …

docs: fix documentation links

---

README.md
docs/index.md

**Issue number:** #154 
Replace occurrences of Slack invitation links with links to the new Discord space.
N/A
<details>
Checklist:
</details>
-----
[View rendered README.md](https://github.com/sthuber90/aws-lambda-powertools-dotnet/blob/add-discord- …

docs(home): add discord invitation link

---

examples/Metrics/README.md

Related issue: https://github.com/awslabs/aws-lambda-powertools-dotnet/issues/162
Fixed a small typo in the Metrics example title for future readers.
Only docs change.
<details>
No.
Checklist:
</details>
-----
[View rendered …

docs: typo in metrics README

---

.github/ISSUE_TEMPLATE/share_your_work.yml
.github/ISSUE_TEMPLATE/support_powertools.yml
docs/core/logging.md
docs/core/metrics.md
docs/index.md
docs/javascript/extra.js
docs/references.md
docs/we_made_this.md
mkdocs.yml
poetry.lock

**Issue number:** #165
Updates and fixes to docs. 
- fix: metrics formatting issue
- fix: updated environmental variables in samples to PascalCase as default
- feat: updated homepage content
<details>
Checklist:
</details>

chore(docs): updated documentation

---

examples/Logging/template-docker.yaml
examples/Logging/template.yaml
examples/Metrics/template-docker.yaml
examples/Metrics/template.yaml
examples/Tracing/template-docker.yaml
examples/Tracing/template.yaml

**Issue number:** #176 
Pascal casing used by default in example projects
Changed `POWERTOOLS_LOGGER_CASE` environment variable from `SnakeCase` to `PascalCase` in sample projects.
Casing will be Pascal case by default for log entries.
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might …

fix: updated logger casing env vars in samples

---

.github/ISSUE_TEMPLATE/config.yaml
.github/scripts/comment_on_large_pr.js
.github/scripts/enforce_acknowledgment.js
.github/scripts/label_pr_based_on_title.js
.github/scripts/label_related_issue.js
.github/workflows/build.yml
.github/workflows/build_changelog.yml
.github/workflows/on_label_added.yml
.github/workflows/on_push_docs.yml
.github/workflows/rebuild_latest_docs.yml
.github/workflows/release-drafter.yml
.github/workflows/reusable_export_pr_details.yml
.github/workflows/reusable_publish_changelog.yml
.github/workflows/reusable_publish_docs.yml

**Issue number:** #180 
Updated build and other actions
- fix: removed duplicate template issue
- chore(ci): updating actions
- chore: updated setup-dotnet@v1 to setup-dotnet@v3
N/A
<details>
Checklist:
</details>

chore(ci): updated workflows

---

CHANGELOG.md
examples/Logging/src/HelloWorld/HelloWorld.csproj
examples/Metrics/src/HelloWorld/HelloWorld.csproj
examples/Tracing/src/HelloWorld/HelloWorld.csproj

**Issue number:** 184
Update NuGet references for examples projects
Update to version 0.0.2-preview
<details>
Checklist:
</details>

fix: update NuGet references for examples

---

CHANGELOG.md
examples/Logging/src/HelloWorld/HelloWorld.csproj
examples/Metrics/src/HelloWorld/HelloWorld.csproj
examples/Tracing/src/HelloWorld/HelloWorld.csproj
version.json

**Issue number:** 184
Sync main with develop for NuGet references for examples update post release v0.0.2-preview
Example NuGet Package
<details>
Checklist:
</details>

chore(ci): merge develop to main for NuGet references for examples update

---

libraries/src/AWS.Lambda.Powertools.Logging/Internal/LoggerProvider.cs
libraries/src/AWS.Lambda.Powertools.Logging/LoggerConfiguration.cs
libraries/src/AWS.Lambda.Powertools.Logging/LoggerExtensions.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Serializer/JsonNamingPolicyDecorator.cs

**Issue number**: #191
* Updated crefs to have the fully qualified name of the type
<details>
**RFC issue number**: #191 
Checklist:
</details>

chore(docs): fix incorrect crefs

---

libraries/src/AWS.Lambda.Powertools.Logging/Internal/PowertoolsLogger.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs

Issue number: #201
Currently the plus sign is escaped and transformed into "\u002B". This is not the expected behaviour because it will break bas64 encoding/decoding.
Added new test that tests a static string that contains + sign when encoded. 
```jsonOptions.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;```
<details>
Checklist:
</details>
**Disclaimer**: We value your time and …

bug: fix flaky test, add relaxed json escaping

---

.github/ISSUE_TEMPLATE/maintenance.yml

Issue number:N/A
Add new issue template for maintenance tasks
New template file
<details>
Checklist:
</details>

chore - New maintenance issue template

---

libraries/src/AWS.Lambda.Powertools.Metrics/Model/Metadata.cs

Issue number: 207
This PR addresses the incorrect metrics timestamp
Timestamp for the context has change to generate a new time every time context flushes and serialises EMF metrics to CloudWatch logs
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might …

fix: Wrong metrics timestamp

---

README.md

Issue number: N/A
Updates Powertools definition for upcoming branding across all languages.
<details>
Checklist:
</details>

docs(home): update powertools definition

---

examples/Metrics/src/HelloWorld/Function.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Internal/MetricsAspectHandler.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Metrics.cs
libraries/src/AWS.Lambda.Powertools.Metrics/MetricsAttribute.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Model/Metadata.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/EMFValidationTests.cs

Issue number: 206
This PR addresses warning messages raised when coldstart up metrics is being captured.
Logic for empty metrics is changed not to show warning when user capture ColdStart metric
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be …

fix: ColdStart capture warning

---

CHANGELOG.md
docs/index.md
version.json

Issue number: #214
This PR changes the version to v1.0.0.o
<details>
Checklist:
</details>

chore: Bump versions for release

---

libraries/src/AWS.Lambda.Powertools.Tracing/Internal/TracingAspectHandler.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/TracingAttributeTest.cs

Fix Tracing when exception is thrown. Prevent Tracing from throwing InvalidOperationException
Issue number: 211
This issue occurs when:
* Tracing feature was enabled and the setting POWERTOOLS_TRACER_CAPTURE_ERROR was set to true
* If there was an exception not handled or an exception thrown in the code
The following exception would occur
```
"errorType": "TargetInvocationException",
"errorMessage": "Exception has been thrown by the target of an invocation.",
"stackTrace": [
"at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)",
"at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)",
"at …
```

Fix Tracing when exception is thrown. Prevent Tracing from throwing InvalidOperationException

---

.chglog/CHANGELOG.tpl.md
.chglog/config.yml
.gitignore
Makefile
README.md

Issue number: #217 
Changelog was not being generated because there was no action in Makefile for changelog.
This Makefile is called from the GitHub action `Build and publish latest changelog` https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/.github/workflows/reusable_publish_changelog.yml
* Changelog in Makefil
* .chglog folder
* with config and template 
Changelog will be updated on release
<details>
Checklist:
</details>
**Disclaimer**: We value your …

chore : add changelog to makefile

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintenance.yml
.github/ISSUE_TEMPLATE/rfc.yml

Issue number: #250 
The Powertools for Python link is missing from the template issues so I added this.
<details>
Checklist:
</details>

chore(governance): add Lambda Powertools for Python in issue templates

---

.github/workflows/dispatch_analytics.yml

Skip analytics job entirely if running on forks.
Issue number: #263
Skip analytics job entirely if running on forks.
PS: Looked at my fork and it's the only job that fails so skipping that one only.
<details>
Checklist:
</details>

chore(ci): skip analytics on forks

---

libraries/src/AWS.Lambda.Powertools.Parameters/AWS.Lambda.Powertools.Parameters.csproj
version.json

Issue number: #270 
This PR adds AWS Icon to the Parameters NuGet Package
<details>
Checklist:
</details>

fix: parameters nuget icon

---

docs/utilities/parameters.md

Issue number: #272 
Added additional information to documentation
BEFORE
AFTER
<details>
Checklist:
</details>

docs(parameter): adding required permission to SSM provider

---

mkdocs.yml

Update MK docs - add restrict_base_path: false
Issue number: #275
Added restrict_base_path: false to mkdocs.yml.
<details>
Checklist:
</details>

chore(deps): update mkdocs configuration to support pymdown-extensions 10.0

---

CHANGELOG.md

Issue number: #267 
Update changelog

chore: update changelog with latest changes

---

libraries/src/AWS.Lambda.Powertools.Metrics/IMetrics.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Metrics.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Model/Metadata.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Model/MetricDirective.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Model/MetricsContext.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/ClearDimensionsTests.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/EMFValidationTests.cs

Issue number: #292
Add a method to allow users to clear the existing Dimensions.
Added a ClearAllDimensions Method that will clear all dimensions which removes the default set "Service"
<details>
Checklist:
</details>

feat: Add ClearAllDimensions Method 

---

.chglog/config.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintenance.yml
.github/ISSUE_TEMPLATE/rfc.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/dispatch_analytics.yml
.github/workflows/reusable_export_pr_details.yml
.github/workflows/reusable_publish_docs.yml
CHANGELOG.md
MAINTAINERS.md
README.md
apidocs/index.md
apidocs/toc.yml
docs/core/metrics.md
docs/index.md
docs/utilities/parameters.md
libraries/src/AWS.Lambda.Powertools.Common/AWS.Lambda.Powertools.Common.csproj
libraries/src/AWS.Lambda.Powertools.Logging/AWS.Lambda.Powertools.Logging.csproj
libraries/src/AWS.Lambda.Powertools.Logging/README.md
libraries/src/AWS.Lambda.Powertools.Metrics/AWS.Lambda.Powertools.Metrics.csproj
libraries/src/AWS.Lambda.Powertools.Metrics/README.md
libraries/src/AWS.Lambda.Powertools.Parameters/AWS.Lambda.Powertools.Parameters.csproj
libraries/src/AWS.Lambda.Powertools.Parameters/README.md
libraries/src/AWS.Lambda.Powertools.Tracing/AWS.Lambda.Powertools.Tracing.csproj
libraries/src/AWS.Lambda.Powertools.Tracing/README.md
mkdocs.yml

> **Warning**
> Do not merge until after the move.
Issue number: #282 
Performed a find & replace for `awslabs/aws-lambda-powertools-dotnet` to `aws-powertools/lambda-dotnet`
Users will be redirected from the current URL to the new URL (https://github.com/aws-powertools/lambda-dotnet).
<details>
Checklist:
</details>
**Disclaimer**: We value …

chore: Change repo URL to the new location

---

libraries/src/AWS.Lambda.Powertools.Metrics/Model/MetricDirective.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/EMFValidationTests.cs

Issue number: #310 
Currently it is possible for the async code to hit a race condition that returns a System.ArgumentException: An item with the same key has already been added.
Add lock to avoid race condition when adding metrics. 
Hold a lock for as short time as possible to reduce lock contention. 
Add tests to test race condition.
<details>
Checklist:
</details>
**Disclaimer**: We value …

fix: Metrics Race condition if using Async calls

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintenance.yml
.github/ISSUE_TEMPLATE/rfc.yml
.github/PULL_REQUEST_TEMPLATE.md
MAINTAINERS.md
README.md
apidocs/index.md
apidocs/toc.yml
docs/index.md
docs/javascript/extra.js
docs/roadmap.md
libraries/src/AWS.Lambda.Powertools.Logging/README.md
libraries/src/AWS.Lambda.Powertools.Metrics/README.md
libraries/src/AWS.Lambda.Powertools.Parameters/README.md
libraries/src/AWS.Lambda.Powertools.Tracing/README.md

Issue number: #290 
Docs urls need to be updated to lambda/<language> so lambda/dotnet instead of lambda-dotnet
update urls to new format. remove latest from .net url
<details>
Checklist:
</details>

chore: update urls to new format. remove latest from .net url

---

examples/Idempotency/.gitignore
examples/Idempotency/PowertoolsIdempotencyExample.sln
examples/Idempotency/README.md
examples/Idempotency/events/event.json
examples/Idempotency/src/HelloWorld/Function.cs
examples/Idempotency/src/HelloWorld/HelloWorld.csproj
examples/Idempotency/src/HelloWorld/aws-lambda-tools-defaults.json
examples/Idempotency/template.yaml
examples/Idempotency/test/HelloWorld.Test/DynamoDbFixture.cs
examples/Idempotency/test/HelloWorld.Test/FunctionTest.cs
examples/Idempotency/test/HelloWorld.Test/HelloWorld.Tests.csproj

Issue number: #299 
Introduce an example for Idempotency utility.
This pull request adds an example solution on how to use Idempotency utility
<details>
Checklist:
</details>

docs: Add Idempotency example

---

.github/dependabot.yml

Issue number: #316 
Enabling dependabot for the repository. This will give us a better understanding of dependency security vulnerabilities and keep up to date with latest versions.
View alerts about dependencies that are known to contain security vulnerabilities, and choose whether to have pull requests generated automatically to update these dependencies. For more information, see "[About Dependabot alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts)" and "[About Dependabot security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates)."
Add dependabot.yml
Follow guide …

chore: Create dependabot.yml to enable dependabot

---

examples/Idempotency/src/HelloWorld/HelloWorld.csproj

Issue number: #300 
Sam build is failing 
`NU1605: Detected package downgrade: AWSSDK.DynamoDBv2 from 3.7.103.7 to 3.7.101.14. Reference the package directly from the
project to select a different version.
... publish: /Users/henrigra/work/aws-lambda-powertools-dotnet/examples/Idempotency/src/HelloWorld/HelloWorld.csproj : error
NU1605:  HelloWorld -> AWS.Lambda.Powertools.Idempotency 0.0.1-preview -> AWSSDK.DynamoDBv2 (>= 3.7.103.7)
... publish: /Users/henrigra/work/aws-lambda-powertools-dotnet/examples/Idempotency/src/HelloWorld/HelloWorld.csproj : error
NU1605:  HelloWorld -> AWSSDK.DynamoDBv2 (>= 3.7.101.14)
... publish:   Failed to restore`
Update DynamoDBv2 version to 3.7.103.7
> Please share what …

chore: Idempotency examples - Update AWSSDK.DynamoDBv2 version

---

examples/Idempotency/src/HelloWorld/HelloWorld.csproj

Issue number: #300 
Idempotency example failing due to old Logging version
Update Logging version
<details>
Checklist:
</details>

chore: Bump logging version to fix idempotency example

---

docs/utilities/idempotency.md
libraries/src/AWS.Lambda.Powertools.Idempotency/IdempotencyKeyAttribute.cs
libraries/src/AWS.Lambda.Powertools.Idempotency/IdempotentAttribute.cs
libraries/src/AWS.Lambda.Powertools.Idempotency/Persistence/BasePersistenceStore.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Handlers/IdempotencyInternalFunction.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Handlers/IdempotencyInternalFunctionInternalKey.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Handlers/IdempotencyInternalFunctionInvalid.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Handlers/IdempotencyInternalFunctionVoid.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Internal/IdempotentAspectTests.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Internal/InMemoryPersistenceStore.cs

Issue number: #348
Update the IdempotentAttribute to get the payload based on the following:
- If the method only has one parameter, it will be used by default. 
- If there are 2 or more parameters, you must set the `IdempotencyKey` attribute on the parameter to use.
```csharp
public class Function
{
public Function()
{
Idempotency.Configure(builder => builder.UseDynamoDb("idempotency_table"));
}
public Task<string> FunctionHandler(string input, ILambdaContext context)
{
dummpy("hello", "world")
return Task.FromResult(input.ToUpper());
}
[Idempotent]
private string dummy(string argOne, [IdempotencyKey] string argTwo) {
return "something";
}
}
```
<details>
**RFC issue …

feat: idempotent function

---

docs/core/logging.md
libraries/src/AWS.Lambda.Powertools.Logging/ILogFormatter.cs
libraries/src/AWS.Lambda.Powertools.Logging/Internal/PowertoolsLogger.cs
libraries/src/AWS.Lambda.Powertools.Logging/LogEntry.cs
libraries/src/AWS.Lambda.Powertools.Logging/LogEntryLambdaContext.cs
libraries/src/AWS.Lambda.Powertools.Logging/LogFormatException.cs
libraries/src/AWS.Lambda.Powertools.Logging/Logger.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/LogFormatterTest.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs

Issue number: #366
This PR allows users to being their own log formatter
No changes to exiting functionalities only adding a new feature.
```c#
/**
* Handler for requests to Lambda function.
*/
public class Function
{
/// <summary>
/// Function constructor
/// </summary>
public Function()
{
Logger.UseFormatter(new CustomLogFormatter());
}
[Logging(CorrelationIdPath = "/headers/my_request_id_header", SamplingRate = 0.7)]
public async Task<APIGatewayProxyResponse> FunctionHandler
(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
{
...
}
}
```
CustomLogFormatter implementation
```c#
public class CustomLogFormatter : ILogFormatter
{
public object FormatLogEntry(LogEntry logEntry)
{
return new
{
Message = logEntry.Message,
Service = logEntry.Service,
CorrelationIds = new 
{ …
```

feat: Add bring your own log formatter to logger

---

.github/dependabot.yml

disable dependabot
https://github.com/dependabot/dependabot-core/issues/4999
> Please provide the issue number 
Issue number: #463 
Disable dependabot until https://github.com/dependabot/dependabot-core/issues/4999 is supported
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be …

chore: Disable dependabot.yml

---

.github/ISSUE_TEMPLATE/maintenance.yml
README.md
docs/index.md
version.json

Issue number: https://github.com/aws-powertools/powertools-lambda-dotnet/issues/488
This PR includes the required changes for release of batch processing feature
Include Batch Processing in Versions.json file
Add documentation
Allows user to include & use batch processing in preview
<details>
Checklist:
</details>

chore: Include release for batch processing feature

---

libraries/src/AWS.Lambda.Powertools.BatchProcessing/README.md
libraries/src/AWS.Lambda.Powertools.Common/README.md
libraries/src/AWS.Lambda.Powertools.Idempotency/README.md
libraries/src/AWS.Lambda.Powertools.Logging/README.md
libraries/src/AWS.Lambda.Powertools.Metrics/README.md
libraries/src/AWS.Lambda.Powertools.Parameters/README.md
libraries/src/AWS.Lambda.Powertools.Tracing/README.md

Issue number: #488 
Update Nuget packages Readme
Add Readme for Batch
Fix links
<details>
Checklist:
</details>

chore: Update projects readme for nuget

---

docs/core/metrics.md
libraries/src/AWS.Lambda.Powertools.Metrics/Model/Metadata.cs
libraries/src/AWS.Lambda.Powertools.Metrics/Model/RootNode.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/EMFValidationTests.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandler.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandlerTests.cs

Issue number: #504 
There are two issues when calling Metrics.AddMetadata
- If the same key is used on the Metrics.AddMetric and on the Metrics.AddMetadata - it will throw the An item with the same key has already been added exception
- On the second Lambda invocation it will throw the An item with the same key has already been added exception
- Clear Metadata dictionary when clearing metrics after flush, this prevents issue on second call having an existing key. 
- Move metadata node serialization to bottom, and try add, if it fails ignore, this fixes the Metrics and Metadata having the same key. Metadata is ignored 
- Add tests
> Please share what the user experience looks like before and after this …

fix: Metrics throws exception when using AddMetadata

---

version.json

Issue number: #506 
Update versions for release 1.8.1
Logging: 1.3.3
Metrics: 1.4.3
In this release we are happy to introduce two new converters for DateOnly and TimeOnly types. These are not supported by default on .NET 6 but will be included in Powertools.
We also fixed two bugs reported on the metrics utility.
- Do not throw exception when decorating a non Lambda handler method
- Do not throw exception when Metadata uses and existing metrics key
- Do not throw exception on second invocation when using Metadata
<details>
Checklist: …

chore: Update versions for release 1.8.1

---

docs/core/logging.md
libraries/src/AWS.Lambda.Powertools.Common/Core/Constants.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/IPowertoolsConfigurations.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/PowertoolsConfigurations.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/SystemWrapper.cs
libraries/src/AWS.Lambda.Powertools.Logging/Internal/PowertoolsConfigurations.cs
libraries/src/AWS.Lambda.Powertools.Logging/Internal/PowertoolsLogger.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Utilities/SystemWrapperMock.cs

Issue number: #515 
<details>
Checklist:
</details>

feat: New log level

---

libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Handlers/IdempotencyFunctionMethodDecorated.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/IdempotencyTest.cs
libraries/tests/AWS.Lambda.Powertools.Idempotency.Tests/Internal/IdempotentAspectTests.cs

Issue number: #512
We were missing a test for the E2E journey when decorating a method and not the handler
Add missing E2E tests
<details>
Checklist:
</details>

chore: add e2e tests for idempotency method

---

docs/core/logging.md
examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj
examples/Idempotency/src/HelloWorld/HelloWorld.csproj
examples/Logging/src/HelloWorld/HelloWorld.csproj
examples/Metrics/src/HelloWorld/HelloWorld.csproj
examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj
examples/Tracing/src/HelloWorld/HelloWorld.csproj

Issue number: #517 
Update examples for release 1.8.2
<details>
Checklist:
</details>

chore: update examples for 1.8.2 release

---

docs/utilities/batch-processing.md

Issue number: #546
Install steps for batch processing in the docs
Add install step
<details>
Checklist:
</details>

chore: Update batch-processing docs

---

docs/utilities/parameters.md
libraries/src/AWS.Lambda.Powertools.Parameters/AWS.Lambda.Powertools.Parameters.csproj
libraries/src/AWS.Lambda.Powertools.Parameters/AppConfig/AppConfigProvider.cs
libraries/src/AWS.Lambda.Powertools.Parameters/AppConfig/AppConfigProviderConfigurationBuilder.cs
libraries/src/AWS.Lambda.Powertools.Parameters/AppConfig/IAppConfigProvider.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigDictionaryTransformer.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigFeatureFlagHelper.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigJsonConfigurationParser.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigProviderCacheHelper.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigProviderConfiguration.cs
libraries/src/AWS.Lambda.Powertools.Parameters/Internal/AppConfig/AppConfigResult.cs
libraries/src/AWS.Lambda.Powertools.Parameters/ParametersManager.cs
libraries/src/Directory.Packages.props
libraries/tests/AWS.Lambda.Powertools.Parameters.Tests/AppConfig/AppConfigProviderTest.cs

Issue number: #558
This PR enhanced the parameters utility functionality and adds support for AppConfig and FeatureFlags
Parameters utility has been modified to add support for AppConfig 
```c#
// Get AppConfig Provider instance
IAppConfigProvider appConfigProvider = ParametersManager.AppConfigProvider
.DefaultApplication("MyApplicationId")
.DefaultEnvironment("MyEnvironmentId")
.DefaultConfigProfile("MyConfigProfileId");
// Retrieve a single configuration, latest version
IDictionary<string, string?> value = await appConfigProvider
.GetAsync()
.ConfigureAwait(false);
// Check if feature flag is enabled
var isFeatureFlagEnabled = await appConfigProvider
.IsFeatureFlagEnabledAsync("MyFeatureFlag")
.ConfigureAwait(false);
if (isFeatureFlagEnabled)
{
// Retrieve an attribute value of the …
```

feat: Add AppConfig parameter provider

---

libraries/src/AWS.Lambda.Powertools.Common/Aspects/UniversalWrapperAspect.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/Handlers/FunctionHandlerForGeneric.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/Handlers/HandlerTests.cs

Issue number: #571 
Decorating a generic method with Tracing utility and calling that method more than once with different T would cause an exception, because the T that we cache would mismatch the new T resulting in `System.InvalidCastException`.
The fix is to change the cache key to use the full method name coming from the target method that was decorated, this will take into account the T, return T and T parameters making the key unique.
Added tests to validate generic method decoration.
<details>
Checklist:
</details>
By submitting …

fix: Error when decorating duplicate generic method - Tracing

---

.github/workflows/build.yml

Update setup dotnet and codecov actions
Issue number: #583
Update build pipeline actions for setupdotnet and codecov
- actions/setup-dotnet to 4.0.0
- codecov/codecov-action to 4.3.1
<details>
Checklist:
</details>

chore: Update build pipeline

---

libraries/src/AWS.Lambda.Powertools.Idempotency/AWS.Lambda.Powertools.Idempotency.csproj
libraries/src/Directory.Build.targets
version.json

Issue number: #585 
Issue when packaging the Idempotency Nuget package now that we target multiple frameworks due to the open issue on the Nuget repository https://github.com/NuGet/Home/issues/3891
Manually adding the JMESPath dll to the output so it is available on the Idempotency Nuget package.
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull …

chore: Fix jmespath dependency

---

libraries/src/AWS.Lambda.Powertools.Metrics/Metrics.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandler.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandlerTests.cs

Issue number: #593 
When PowertoolsConfigurations.MaxMetrics is set to a lower number and using multi threaded operations AddMetric will throw the following exception.
```csharp
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNext()
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at AWS.Lambda.Powertools.Metrics.Metrics.AWS.Lambda.Powertools.Metrics.IMetrics.AddMetric(String key, Double value, MetricUnit unit, MetricResolution metricResolution) in C:\Users\jesse.poulton\repos\powertools-lambda-dotnet\libraries\src …
```

chore: Metrics - Add thread safety to AddMetric

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/label_pr_on_title.yml
.github/workflows/on_label_added.yml
.github/workflows/on_merged_pr.yml
.github/workflows/on_opened_pr.yml
.github/workflows/record_pr.yml
.github/workflows/reusable_export_pr_details.yml
.github/workflows/reusable_publish_changelog.yml
.github/workflows/reusable_publish_docs.yml
.github/workflows/secure_workflows.yml

Issue number: #604
update codecov version
<details>
Checklist:
</details>

chore: Update codecov

---

examples/AOT/src/AOT/AOT.csproj
examples/AOT/src/AOT/Function.cs
examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj
examples/Tracing/src/HelloWorld/HelloWorld.csproj

Issue number: #619 
Update examples for Tracing 1.5.0
Add Tracing to AOT examples project
<details>
Checklist:
</details>

chore: Update examples Tracing to version 1.5.0 related to release 1.12

---

README.md
docs/index.md

Issue number: #621
Add Caylent customer reference on behalf of Randall Hunt
<details>
Checklist:
</details>

chore: add caylent as a public reference

---

libraries/src/AWS.Lambda.Powertools.BatchProcessing/RecordHandlerResult.cs
libraries/src/AWS.Lambda.Powertools.Tracing/Internal/TracingAspect.cs
libraries/src/AWS.Lambda.Powertools.Tracing/Internal/XRayRecorder.cs
libraries/src/Directory.Packages.props
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/Handlers/Handlers.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/TracingAttributeTest.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/XRayRecorderTests.cs

Issue number: #630 
- Update RecordHanderResult to avoid object cycle on static property, this was breaking LitJson parser on X-Ray SDK with Max allowed object depth reached.
- Tracing  now takes into account the CaptureMode set for each method
- XRayRecorder now captures the exceptions from EndSubsegment call and does not surface exception to the client
- Update nuget packages for X-Ray SDK
Now when exceptions occour inside X-Ray SDK EndSubsegment we catch those and create a new SubSegment in CloudWatch Traces, this prevents the app from crashing.
<details>
<summary>Is this a breaking …

chore: Fix Max depth serialization bug when using Batch RecordHanderResult and Tracing 

---

docs/core/tracing.md

Issue number: #619 
Fix typo in docs
<details>
Checklist:
</details>

chore(docs): Updating tracing docs for typo

---

libraries/src/AWS.Lambda.Powertools.BatchProcessing/AWS.Lambda.Powertools.BatchProcessing.csproj
libraries/src/AWS.Lambda.Powertools.Idempotency/AWS.Lambda.Powertools.Idempotency.csproj
libraries/src/AWS.Lambda.Powertools.Logging/AWS.Lambda.Powertools.Logging.csproj
libraries/src/AWS.Lambda.Powertools.Metrics/AWS.Lambda.Powertools.Metrics.csproj
libraries/src/AWS.Lambda.Powertools.Parameters/AWS.Lambda.Powertools.Parameters.csproj
libraries/src/AWS.Lambda.Powertools.Tracing/AWS.Lambda.Powertools.Tracing.csproj
libraries/src/Directory.Build.targets

Issue number: #626 
This change will stop the copy of common for each project and do that at build time only.
This setup simplifies the configuration, it treats Common and JMESPath as implementation details of the **Idempotency** package.
This approach should:
- Include Common and JMESPath for compilation in the Idempotency project
- Not copy the Common and JMESPath DLLs to the output directory of projects that reference Idempotency
- Ensure that when the Idempotency package is created, it includes the necessary parts of Common and JMESPath
- Work consistently across Debug and Release builds
Replace `PrivateAssets=all` and simplify Directory.Build.targets.
with 
```
<Private>false</Private>
<ExcludeAssets>runtime</ExcludeAssets>
```
This comes after …

chore: Change the way we reference Common and JMESPath (internal references).

---

docs/core/logging.md
examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj
examples/BatchProcessing/test/HelloWorld.Test/HelloWorld.Tests.csproj
examples/Idempotency/src/HelloWorld/HelloWorld.csproj
examples/Idempotency/test/HelloWorld.Test/HelloWorld.Tests.csproj
examples/Logging/src/HelloWorld/HelloWorld.csproj
examples/Logging/test/HelloWorld.Test/HelloWorld.Tests.csproj
examples/Metrics/src/HelloWorld/HelloWorld.csproj
examples/Metrics/test/HelloWorld.Test/HelloWorld.Tests.csproj
examples/Parameters/cfn/HelloWorld.Cfn/HelloWorld.Cfn.csproj
examples/Parameters/src/HelloWorld/HelloWorld.csproj
examples/Parameters/test/HelloWorld.Test/HelloWorld.Tests.csproj
examples/Tracing/src/HelloWorld/HelloWorld.csproj
examples/Tracing/test/HelloWorld.Test/HelloWorld.Tests.csproj
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Formatter/LogFormatterTest.cs

Issue number: #628 
Update docs
<details>
Checklist:
</details>

chore: update logging aot docs

---

docs/snippets/batch/templates/dynamodb.yaml
docs/snippets/batch/templates/kinesis.yaml
docs/snippets/batch/templates/sqs.yaml
docs/utilities/batch-processing.md
examples/BatchProcessing/src/HelloWorld/Function.cs
examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj
examples/BatchProcessing/template.yaml
examples/BatchProcessing/test/HelloWorld.Test/HelloWorld.Tests.csproj
libraries/src/AWS.Lambda.Powertools.BatchProcessing/BatchProcessor.cs
libraries/src/AWS.Lambda.Powertools.BatchProcessing/BatchProcessorAttribute.cs
libraries/src/AWS.Lambda.Powertools.BatchProcessing/ProcessingOptions.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/Constants.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/IPowertoolsConfigurations.cs
libraries/src/AWS.Lambda.Powertools.Common/Core/PowertoolsConfigurations.cs
libraries/tests/AWS.Lambda.Powertools.BatchProcessing.Tests/Handlers/SQS/Handler/HandlerFunction.cs
libraries/tests/AWS.Lambda.Powertools.BatchProcessing.Tests/Handlers/SQS/HandlerTests.cs
libraries/tests/AWS.Lambda.Powertools.BatchProcessing.Tests/Helpers/Helpers.cs

Added new batch processing option: `ThrowOnFullBatchFailure` to control if a `BatchProcessingException` should be raised on full batch failure or not.
Issue number: #608 
This PR introduces a new batch processing option: `ThrowOnFullBatchFailure` to control if a `BatchProcessingException` should be raised on full batch failure or not.
The processing option can be set via:
- A new `ThrowOnFullBatchFailure` field on the `BatchProcessor` attribute (applied in non-utility mode).
- A new environment variable `POWERTOOLS_BATCH_THROW_ON_FULL_BATCH_FAILURE` (applied in non-utility mode).
- Directly on the `AWS.Lambda.Powertools.BatchProcessing.ProcessingOptions` in utility mode.
To maintain current behavior, the …

feat: New batch processing option: 'ThrowOnFullBatchFailure'

---

.github/ISSUE_TEMPLATE/bug_report.yml
libraries/src/AWS.Lambda.Powertools.Common/Utils/RuntimeFeatureWrapper.cs
libraries/src/AWS.Lambda.Powertools.Logging/Serializers/PowertoolsLoggingSerializer.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Serializers/PowertoolsLoggingSerializerTests.cs
version.json

Issue number: #656 
Check if the code supports dynamic code, if it does do not add `TypinfoResolver`
Features are now behind `RuntimeFeature.IsDynamicCodeSupported`
<details>
Checklist:
</details>

chore: Remove TypeInfoResolver from non AOT mode.

---

libraries/src/AWS.Lambda.Powertools.Metrics/Model/MetricDirective.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/ClearDimensionsTests.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/EMFValidationTests.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandler.cs
libraries/tests/AWS.Lambda.Powertools.Metrics.Tests/Handlers/FunctionHandlerTests.cs
version.json

Issue number: #662 
Dimensions is now a List<string> and not a List<List<string>>
Added tests
The following example:
```csharp
[Metrics(Namespace = "dotnet-powertools-test", Service = "testService")]
public void AddMultipleDimensions()
{
Metrics.SetDefaultDimensions(new Dictionary<string, string> {
{ "Default", "Initial" }
});
Metrics.PushSingleMetric("Lambda Execute", 1, MetricUnit.Count, metricResolution: MetricResolution.High, nameSpace: "ns1",
defaultDimensions: new Dictionary<string, string> {
{ "Type", "Start" }
});
Metrics.PushSingleMetric("Lambda Execute", 1, MetricUnit.Count, metricResolution: MetricResolution.High,  nameSpace: "ns2",
defaultDimensions: new Dictionary<string, string> {
{ "Type", "Start" },
{ "SessionId", "Unset" }
}); …
```

chore: Fix Metrics EMF to correctly output Dimensions as an array of strings

---

libraries/src/AWS.Lambda.Powertools.Logging/Internal/Helpers/PowertoolsLoggerHelpers.cs
libraries/src/AWS.Lambda.Powertools.Logging/Serializers/LogLevelJsonConverter.cs
libraries/src/AWS.Lambda.Powertools.Logging/Serializers/PowertoolsLoggingSerializer.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Formatter/LogFormatterTest.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Handlers/TestHandlers.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Serializers/PowertoolsLoggingSerializerTests.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Utilities/LogLevelJsonConverterTests.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Utilities/PowertoolsLoggerHelpersTests.cs

Issue number: #656 
Serialize enum types correctly.
Add specific JsonConverter for LogLevel
<details>
Checklist:
</details>

chore: Fix logging enum serialization

---

libraries/src/AWS.Lambda.Powertools.Logging/Internal/Converters/ExceptionConverter.cs
libraries/src/AWS.Lambda.Powertools.Logging/Internal/Converters/ExceptionPropertyExtractor.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs

Issue number: #680 
This pull request focuses on enhancing the logging functionality by improving how exceptions, particularly inner exceptions, are handled and logged. The key changes include refactoring the exception writing logic, updating the property extraction to include inner exceptions, and adding new tests to verify these changes.
* [`libraries/src/AWS.Lambda.Powertools.Logging/Internal/Converters/ExceptionConverter.cs`](diffhunk://#diff-a21277a5724c3b17bfa08a604fa9eaedd7d7aacae6178e0e574e7d276332f111L60-R63): Refactored the `Write` method to include a nested `WriteException` method, which recursively writes inner exceptions if they exist. [[1]](diffhunk://#diff-a21277a5724c3b17bfa08a604fa9eaedd7d7aacae6178e0e574e7d276332f111L60-R63) …

chore: Exception logging to include inner exceptions

---

.github/workflows/e2e-infra-deploy.yml

Issue number: #684 
<details>
Checklist:
</details>

chore: Update e2e-infra-deploy.yml

---

.github/workflows/e2e-tests.yml

Issue number: #684 
<details>
Checklist:
</details>

chore: Update e2e-tests.yml

---

libraries/tests/Directory.Packages.props

… changes
Issue Number : [697](https://github.com/aws-powertools/powertools-lambda-dotnet/issues/697)
The commit updates the Directory.Packages.props file to pin the FluentAssertions NuGet package version by surrounding the version number with square brackets to prevent unintentional upgrades.
<details>
Checklist:
</details>

fix: pin FluentAssertions NuGet version to prevent license issues

---

.github/workflows/e2e-tests.yml
libraries/tests/e2e/functions/core/logging/Function/test/Function.Tests/FunctionTests.cs
libraries/tests/e2e/functions/core/metrics/Function/test/Function.Tests/FunctionTests.cs
libraries/tests/e2e/functions/core/tracing/Function/test/Function.Tests/FunctionTests.cs

Issue number: #683 
Add E2E tests for AOT x86 only. Currently we do not have support for ARM runners
<details>
Checklist:
</details>

chore: Add Aot e2e tests for x86

---

.github/workflows/e2e-tests.yml
libraries/tests/e2e/infra-aot/Program.cs

Issue number: #683
Add GitHub actions strategy to deploy to arm and x86 architecture for AOT end to end tests
Use new GitHub arm runner
Split Cloud Formation AOT stack by architecture (arm, x86)
<details>
Checklist:
</details>

chore: Fix arm e2e aot

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
docs/Dockerfile

Issue number: #705 
We need to enable dependabot to update our actions.
<details>
Checklist:
</details>

chore(ci): add dependabot file

---

.github/workflows/e2e-tests.yml

Issue number: #719
This pull request includes a small change to the `.github/workflows/e2e-tests.yml` file. The change specifies that the end-to-end tests should be triggered on pushes to the `libraries` directory.
* [`.github/workflows/e2e-tests.yml`](diffhunk://#diff-194218c48b9a0cdd03974145733804c2d992ca818529fe2fa69a501d8b5b1cc3R16-R17): Added a path filter to trigger the workflow on pushes to the `libraries` directory.
<details>
Checklist:
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and …

chore: Only run on libraries folder changes

---

libraries/src/AWS.Lambda.Powertools.Logging/Internal/LoggingAspect.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Attributes/LoggingAttributeTest.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Handlers/TestHandlers.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs
libraries/tests/AWS.Lambda.Powertools.Logging.Tests/TestSetup.cs
libraries/tests/e2e/functions/core/logging/Function/test/Function.Tests/FunctionTests.cs

Issue number: #702 
Modified the logger provider initialization, adding new test classes and methods, and updating test setups for better organization and functionality.
* [`libraries/src/AWS.Lambda.Powertools.Logging/Internal/LoggingAspect.cs`](diffhunk://#diff-28773729ae13b16a2bea1c09c17e6d653fceee05b81d2c6ad5d003f9ba5165a1L141-R141): Changed the logger provider initialization to always create a new instance of `LoggerProvider`.
* [`libraries/tests/AWS.Lambda.Powertools.Logging.Tests/Attributes/LoggingAttributeTest.cs`](diffhunk://#diff-4103eca0455fc07cb8b4b5a66eadfd3cdd4c918a00867632ca8833647a5ce716R478-R539): Added new test class `ServiceTests` to verify service name overrides and included additional environment variable cleanup in `Dispose` methods. …

chore: Fix Service override on decorator

---

docs/core/logging.md

Issue number: #702 
Add Logging Service property priority to docs
Service Property Priority Resolution
The root level Service property now correctly follows this priority order:
1. LoggingAttribute.Service (property value set in the decorator)
2. POWERTOOLS_SERVICE_NAME (environment variable)
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull …

chore: add Logging Service property priority to docs

---

libraries/tests/Directory.Build.props
libraries/tests/e2e/Directory.Build.props

Issue number: #723 
<PropertyGroup>
<IsPackable>false</IsPackable>
</PropertyGroup>
<details>
Checklist:
</details>

chore: Update test projects to no be packable

---

.github/workflows/docs.yml

docfx version is only compatible with dotnet 8 or later
Issue number: #733 
Current docfx version used to build api docs is not compatible with dotnet 6, updating to dotnet 8
<details>
Checklist:
</details>

chore: Update api docs build to dotnet 8

---

libraries/src/AWS.Lambda.Powertools.Tracing/Internal/Helpers.cs
libraries/src/AWS.Lambda.Powertools.Tracing/Internal/XRayRecorder.cs
libraries/src/AWS.Lambda.Powertools.Tracing/TracingAttribute.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/Handlers/Handlers.cs
libraries/tests/AWS.Lambda.Powertools.Tracing.Tests/TracingAttributeTest.cs

Issue number: #740 
1. Sanitize SegmentName 
2. Show accepted chars in the SegmentName
This pull request introduces several changes to the AWS Lambda Powertools Tracing library, primarily focusing on sanitizing segment names and updating related tests. The most important changes include the addition of a helper method for sanitizing strings, modifications to the `XRayRecorder` and `TracingAttribute` classes to use this sanitization, and the addition of new test cases to ensure the changes work correctly.
* [`libraries/src/AWS.Lambda.Powertools.Tracing/Internal/Helpers.cs`](diffhunk://#diff-a96509cd7948029c474a5db7716e3ae984dc6c68d4221d0070f6357a1947c7c2R1-R23): Added a new static `Helpers` class with a `SanitizeString` method to remove any characters that …

chore: Tracing Sanitize SegmentName to avoid unsupported characters

---

docs/roadmap.md
mkdocs.yml

Issue number: #756
Update to existing roadmap to reflect the work we will be doing in 2025
ter this change
<details>
Checklist:
</details>

chore: Roadmap 2025 update
