.github/workflows/codeql-analysis.yml
**Issue number:** #125 
Adding codeQl action to provide static code analysis (Github Advanced Security feature) for repo.
Static code analysis will be performed per PR
<details>
Checklist:
</details>
=> feat(ci): codeql static code analysis

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/codeql-analysis.yml, CHANGELOG.md, README.md, docs/index.md, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
**Issue number:** #149 
This PR syncs main branch with the latest develop branch 
<details>
Checklist:
</details>
-----
[View rendered CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/CHANGELOG.md)
[View rendered …
=> ci: sync main with develop

README.md
**Issue number:** #169 
* Fixes a few grammar errors. 
* Updates links to example projects to point to the source, not just the readme file.
* Fixes a few grammar errors. 
* Updates links to example projects to point to the source, not just the readme file.
n/a
<details>
no
</details>
-----
[View rendered README.md](https://github.com/nCubed/aws-lambda-powertools-dotnet/blob/develop/README.md)
=> Fix some grammar; update links to example projects.

.github/ISSUE_TEMPLATE/config.yml, .gitpod.yml, .markdownlint.yaml, CHANGELOG.md, LICENSE-THIRD-PARTY
**Issue number:** #178 
Minor changes/updates to tooling, templates and licensing. 
Added linting, third-party license file, issue template for general enquiries 
N/A
<details>
Checklist:
</details>
=> chore(ci): minor updates, licensing

version.json
**Issue number:** n/a
bumped versions for new release
bumped version to 0.0.2-preview
No change
<details>
Checklist:
</details>
=> chore(ci): bumped version

.github/PULL_REQUEST_TEMPLATE.md
Issue number:N/A
Remove bold from Issue Number, so that it passes label_related_issue.js regex expression.
<details>
Checklist:
</details>
=> chore - Update pr template

.github/auto_assign.yml
Issue number: N/A
Added @hjgraca to list of reviewers
N/A
<details>
Checklist:
</details>
=> chore(ci): updating list of reviewers

examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #214
Update NuGet references for examples projects
Update to version 1.0.0
<details>
Checklist:
</details>
=> fix: update NuGet references for examples

docs/core/metrics.md
Metrics Count and sample [ update
Issue number: #224
MetricsUnit Count was updated from COUNT -> Count.
Just Metrics page sample code has been updated.
User experience would be better with the exact code in the sample.
* [ X] [Meets tenets criteria](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
* [ X] I have performed a self-review of this change
<details>
<summary>Is this a breaking change?</summary> NO
Checklist:
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> chore(docs) - Metrics doc updates

CHANGELOG.md
Issue number: #238 
Update changelog
<details>
Checklist:
</details>
=> update changelog with latest changes

version.json
Issue number: #252 
Release version v1.1.0
<details>
Checklist:
</details>
=> chore: Bump versions for release v1.1.0

libraries/tests/AWS.Lambda.Powertools.Common.Tests/Core/PowertoolsEnvironmentTest.cs
Issue number: #213 
Remove real tests against environment variables
<details>
Checklist:
</details>
=> fix: Update PowertoolsEnvironmentTest.cs

libraries/tests/AWS.Lambda.Powertools.Common.Tests/Core/PowertoolsEnvironmentTest.cs, version.json
Issue number: https://github.com/awslabs/aws-lambda-powertools-dotnet/issues/252
Sync main with develop prior to release
<details>
Checklist:
</details>
=> chore: Sync main with develop

version.json
Issue number: #257 
Release version 1.2.0
<details>
Checklist:
</details>
=> chore: Bump versions for release 1.2.0

examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #257 
Update examples version to 1.2.0 release
Update examples version to 1.2.0 release
<details>
Checklist:
</details>
=> chore: bump examples version to 1.2.0 release

version.json
Issue number: #267 
Release version 1.3.0 adds Parameters utility version 0.0.1-preview
<details>
Checklist:
</details>
=> chore: Add parameters utilities into versions.json file for for release 1.3.0

.github/CODEOWNERS, .github/auto_assign.yml, .github/boring-cyborg.yml, .github/release-drafter.yml, MAINTAINERS.md, docs/roadmap.md
Issue number: #290 
Update roadmap and maintainers documentation
Update roadmap links and add additional wording
Add Henrique to maintainers
Update some workflows
<details>
Checklist:
</details>
=> docs: Update roadmap and maintainers

version.json
Issue number: #296 
Summary
Bump the versions and release version 1.4.0
Why is this needed?
Release 1.4.0 includes following packages
Common v1.1.1
Logging v1.1.1
Metrics v1.3.1
Tracing: v1.1.1
Parameters v0.0.2-preview
Idempotency v0.0.1-preview
Which area does this relate to?
Tracer, Logger, Metrics, Parameters, Idempotency
=> maintenance: Update version.json

CHANGELOG.md
Issue number: #296 
update changelog
<details>
Checklist:
</details>
=> chore: update changelog with latest changes

version.json
Issue number: #323 
Bump the versions and release version 1.4.1
Release 1.4.1 includes following packages:
- Metrics v1.3.2
<details>
Checklist:
</details>
=> chore: Update version.json

.github/boring-cyborg.yml
Update text and add batch
Issue number: #290 
Update boring cyborg
Update text and add batch utility
<details>
Checklist:
</details>
=> chore: Update boring-cyborg

.github/dependabot.yml
Issue number: #316 
Update dependabot
<details>
Checklist:
</details>
=> chore: Update dependabot.yml examples

version.json
Issue number: #382 
Update for release 1.4.2
<details>
Checklist:
</details>
=> chore: Update version.json for release 1.4.2

examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Logging/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Metrics/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Parameters/cfn/HelloWorld.Cfn/HelloWorld.Cfn.csproj, examples/Parameters/src/HelloWorld/HelloWorld.csproj, examples/Parameters/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/ServerlessApi/test/LambdaPowertoolsAPI.Tests/LambdaPowertoolsAPI.Tests.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj, examples/Tracing/test/HelloWorld.Test/HelloWorld.Tests.csproj
Issue number: #382 
Bump samples NuGet versions for example projects post release 1.4.2
Bump samples NuGet versions for example projects post release 1.4.2
N/A
<details>
Checklist:
</details>
=> chore(deps): bump examples NuGet versions

version.json
Issue number: #429
Increase the versions for release 1.6.0
version file updated to reflect the change
<details>
Checklist:
</details>
=> chore: Update version release 1.6.0

docs/utilities/parameters.md
Issue number: #429
Remove parameters in preview warning
Remove the warning section in the parameters document
N/A
<details>
Checklist:
</details>
=> chore: Remove Parameters in preview warning

version.json
Issue number: #463 
Increase the versions for release 1.7.0
Version file updated to reflect the change. 
Removed common versioning
<details>
Checklist:
</details>
=> chore: Update version release 1.7.0

examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Parameters/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #463 
Update examples to new nuget packages
<details>
Checklist:
</details>
=> chore: Update examples 1.7.0

version.json
Issue number: #481 
Update versions for release
<details>
Checklist:
</details>
=> chore: Update version for release 1.7.1

version.json
Signed-off-by: Henrique Graca <999396+hjgraca@users.noreply.github.com>> Please provide the issue number
Issue number: #481 
Sync branches
<details>
Checklist:
</details>
=> chore: Sync develop to main for release

examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #506 
Update examples for release 1.8.1
Logging: 1.3.3
Metrics: 1.4.3
<details>
Checklist:
</details>
=> chore: Update examples for release 1.8.1

version.json
Issue number: #517 
<details>
Checklist:
</details>
=> chore: Update version for 1.8.2

examples/Idempotency/src/HelloWorld/HelloWorld.csproj
Issue number: #524 
Update idempotency examples to 1.0.0
<details>
Checklist:
</details>
=> chore: Update examples idempotency

README.md, docs/index.md, docs/utilities/batch-processing.md, version.json
Issue number: #531 
BatchProcessing GA release
Version update for release
Update docs
<details>
Checklist:
</details>
=> chore: Update version for batch GA

docs/core/tracing.md
Auto-disable when not running in AWS Lambda environment
Issue number: #543 
Auto-disable when not running in AWS Lambda environment
Add Auto-disable when not running in AWS Lambda environment to docs
<details>
Checklist:
</details>
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might …
=> chore: Update tracing.md - Auto-disable when not running in AWS Lambda environment

version.json
Issue number: #550 
Update version for release.
Since build is changing and now all utilities support dotnet 8, bumping all versions
<details>
Checklist:
</details>
=> chore: Update version for release 185

libraries/src/AWS.Lambda.Powertools.Idempotency/AWS.Lambda.Powertools.Idempotency.csproj, libraries/src/AWS.Lambda.Powertools.Tracing/AWS.Lambda.Powertools.Tracing.csproj, libraries/src/Directory.Packages.props, libraries/tests/AWS.Lambda.Powertools.BatchProcessing.Tests/Helpers/Helpers.cs, libraries/tests/AWS.Lambda.Powertools.Logging.Tests/AWS.Lambda.Powertools.Logging.Tests.csproj, libraries/tests/Directory.Packages.props
Issue number: #560 
This PR update NuGet packages to the latest versions
NuGet packages versions
No Change
<details>
Checklist:
</details>
=> chore: Update NuGet packages to the latest

version.json
Issue number: #562 
Update version for release.
Since NuGet packages are updated for all utilities bumping all versions
AppConfig provider added to Parameters Utility bumping Parameters version
N/A
<details>
Checklist:
</details>
=> chore: Update version for release 1.9.0

examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj, examples/BatchProcessing/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Logging/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/Metrics/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/Parameters/cfn/HelloWorld.Cfn/HelloWorld.Cfn.csproj, examples/Parameters/src/HelloWorld/HelloWorld.csproj, examples/Parameters/test/HelloWorld.Test/HelloWorld.Tests.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/ServerlessApi/test/LambdaPowertoolsAPI.Tests/LambdaPowertoolsAPI.Tests.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj, examples/Tracing/test/HelloWorld.Test/HelloWorld.Tests.csproj
Issue number: #560 
Update examples dependencies to latest
update nuget packages
<details>
Checklist:
</details>
=> chore: update package versions for examples

version.json
Issue number: #585 
Update Idempotency version to 1.2.0 for release 1.10.0
Update Idempotency version to 1.2.0 for release 1.10.0
<details>
Checklist:
</details>
=> chore: Update idempotency version for release 1.10.0

version.json
Issue number: #595 
Release 1.10.1
Metrics release 1.6.2
Bug fix #594 
<details>
Checklist:
</details>
=> chore: Update version for release 1.10.1

examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj
Issue number: #595 
Update examples for release 1.10.1
Metrics 1.6.2
<details>
Checklist:
</details>
=> chore: Update examples for release 1.10.1

README.md, docs/index.md
Issue number: #631 
Lance French, Engineering Manager, opened a https://github.com/aws-powertools/powertools-lambda-dotnet/issues/631 to add [Pushpay](https://pushpay.com/) as a public reference for Powertools for AWS Lambda.
<details>
Checklist:
</details>
=> chore: Add Pushpay as a public reference

docs/index.md
Issue number: #633 
Fix missing closing tag after public references section
<details>
Checklist:
</details>
=> chore: fix docs missing closing tag

docs/index.md, libraries/src/AWS.Lambda.Powertools.BatchProcessing/AWS.Lambda.Powertools.BatchProcessing.csproj, libraries/src/AWS.Lambda.Powertools.Idempotency/AWS.Lambda.Powertools.Idempotency.csproj, libraries/src/AWS.Lambda.Powertools.Logging/AWS.Lambda.Powertools.Logging.csproj, libraries/src/AWS.Lambda.Powertools.Metrics/AWS.Lambda.Powertools.Metrics.csproj, libraries/src/AWS.Lambda.Powertools.Parameters/AWS.Lambda.Powertools.Parameters.csproj, libraries/src/AWS.Lambda.Powertools.Tracing/AWS.Lambda.Powertools.Tracing.csproj, libraries/src/Directory.Build.targets
Issue number: #636 
<details>
Checklist:
</details>
=> chore: sync main with dev for release 1.13

examples/AOT/src/AOT/AOT.csproj, examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #636 
Update examples for release
- Idempotency v1.2.2
- Batch v1.1.2
- Tracing v1.5.1
<details>
Checklist:
</details>
=> chore: Update examples for release 1..13

examples/AOT/AOT_Logging/src/AOT_Logging/AOT_Logging.csproj, examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #647 
Update Logging nuget package version to 1.6.0
<details>
Checklist:
</details>
=> chore: update logging nuget package version v 1.6.0

.github/workflows/e2e-infra-deploy.yml, .github/workflows/e2e-infra-destroy.yml
Issue number: #684 
<details>
Checklist:
</details>
=> chore: Add workflow call to e2e tests

.github/workflows/e2e-infra-deploy.yml, .github/workflows/e2e-infra-destroy.yml
Issue number: #685 
<details>
Checklist:
</details>
=> chore: Update e2e-infra-deploy.yml

examples/AOT/AOT_Logging/src/AOT_Logging/AOT_Logging.csproj, examples/AOT/AOT_Tracing/src/AOT_Tracing/AOT_Tracing.csproj, examples/BatchProcessing/src/HelloWorld/HelloWorld.csproj, examples/Idempotency/src/HelloWorld/HelloWorld.csproj, examples/Logging/src/HelloWorld/HelloWorld.csproj, examples/Metrics/src/HelloWorld/HelloWorld.csproj, examples/ServerlessApi/src/LambdaPowertoolsAPI/LambdaPowertoolsAPI.csproj, examples/Tracing/src/HelloWorld/HelloWorld.csproj
Issue number: #676 
Update examples versions for Logging and Tracing
<details>
Checklist:
</details>
=> chore: Update dependencies for examples release 1.17

.github/workflows/e2e-tests.yml
Issue number: #712 
<details>
Checklist:
</details>
=> chore: Add concurrency to e2e workflow

mkdocs.yml
Issue number: #746 
This pull request includes a small change to the `mkdocs.yml` file. The change adds the `privacy` plugin to the list of Markdown extensions.
* [`mkdocs.yml`](diffhunk://#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R88): Added the `privacy` plugin to the list of Markdown extensions.
<details>
Checklist:
</details>
**Disclaimer**: We value your time and …
=> chore: Add privacy plugin to mkdocs

docs/utilities/idempotency.md
Issue number: #745 
Docs for custom prefix
<details>
Checklist:
</details>
=> chore: Update docs Idempotency custom prefix
